{{- if or .Values.global.injectPullSecret (and .Values.global.provider.registry.credential.required .Values.operator.enabled) }}
{{- $_ := required "Docker Repository FQDN path is required" .Values.global.provider.registry.fqdn }}
{{- $_ := required "Username information for Docker registry to pull images" .Values.global.provider.registry.credential.username }}
{{- $_ := required "Password information for Docker registry to pull images" .Values.global.provider.registry.credential.password }}
apiVersion: v1
kind: Secret
metadata:
  labels:
     heritage: {{ .Release.Service }}
     release: {{ .Release.Name }}
     chart: {{ template "confluent-operator.chart" . }}
     app: {{ template "confluent-operator.name" . }}
  namespace: {{ .Release.Namespace }}
  name: confluent-docker-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "confluent-operator.imagePullSecret" . | b64enc }}
{{- end }}

