apiVersion: v1
description: A Helm chart for Kubernetes to deploy Confluent Manager
name: manager
version: 1.0.0
appVersion: "1.0"
keywords:
- Confluent Manager
- Confluent
home: https://www.confluent.io/
engine: gotpl
namespace: confluent-operator
sources:
  - https://docs.confluent.io/current/index.html
maintainers:
  - name: Confluent Cloud
    email: operator@confluent.io
tillerVersion: ">=2.9"