apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterrole-minimum
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  - namespaces
  - persistentvolumeclaims
  - pods
  - secrets
  - serviceaccounts
  - services
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - statefulsets
  - statefulsets/scale
  - statefulsets/status
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - 'deployments'
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  - customresourcedefinitions/status
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - 'clusterroles'
  - 'clusterrolebindings'
  verbs:
  - '*'
- apiGroups:
  - "storage.k8s.io"
  resources:
  - 'storageclasses'
  verbs:
  - '*'
- apiGroups:
  - cluster.confluent.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - operator.confluent.cloud
  resources:
  - '*'
  verbs:
  - '*'