{{- $_ := required "api username" .Values.global.sasl.plain.username }}
{{- $_ := required "api password" .Values.global.sasl.plain.password }}
apiVersion: v1
kind: Secret
metadata:
  {{- include "confluent-operator.labels" . }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}-apikeys
type: Opaque
data:
  apikeys.json : {{ include "confluent-operator.apikeys" . | b64enc }}