# remove once, operator deletes the pdb when cleanup
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  annotations:
    helm.sh/hook: post-upgrade, post-install
    helm.sh/hook-delete-policy: "before-hook-creation"
  labels:
    namespace: {{ .Release.Namespace }}
    type: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- $count :=  div (sub (.Values.replicas | int ) 1) 2 }}
  maxUnavailable: {{ $count }}
  selector:
    matchLabels:
      namespace: {{ .Release.Namespace }}
      type: {{ .Values.name }}