apiVersion: v1
imagePullSecrets:
  - name: confluent-docker-registry
kind: ServiceAccount
metadata:
  {{- include "confluent-operator.labels" . }}
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}