kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  {{- include "confluent-operator.labels" . }}
  name: {{ .Release.Namespace }}-{{ .Values.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
{{- if contains "gcp" .Values.global.provider.name }}
  name: cluster-admin
{{- else }}
  name: {{ .Values.name }}
{{- end }}
  apiGroup: rbac.authorization.k8s.io
