apiVersion: v1
kind: Secret
metadata:
  {{- include "confluent-operator.labels" . }}
  namespace: {{ .Release.Namespace }}
  name: operator-licensing
type: Opaque
data:
  licenseKey: {{ .Values.licenseKey | b64enc }}
  publicKey: {{ .Values.publicKey | b64enc }}