apiVersion: v1
{{- if and .Values.global.provider.registry.credential.required .Values.enabled }}
imagePullSecrets:
  - name: confluent-docker-registry
{{- end }}
kind: ServiceAccount
metadata:
  {{- include "confluent-operator.labels" . }}
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}