kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  {{- include "confluent-operator.labels" . }}
  name: {{ .Values.name }}-rolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
